"use client";
import {useEffect,useState} from "react";
import CandlestickChart from "../components/CandlestickChart";
import SignalOverlay from "../components/SignalOverlay";
import BacktestResults from "../components/BacktestResults";
import ExperimentTable from "../components/ExperimentTable";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Candle={timestamp:string;open:string;high:string;low:string;close:string;volume:string}; type Event={event:string;timestamp:string;price:string|number};
type Comparison={experiment_id:string;strategy_version:string;trade_count:number;total_return:string;max_drawdown:string;win_rate:string;profit_factor:string|null};
export default function Dashboard(){const [symbol,setSymbol]=useState("NIFTY"),[start,setStart]=useState("2026-01-02T09:15:00Z"),[end,setEnd]=useState("2026-01-02T15:30:00Z"),[candles,setCandles]=useState<Candle[]>([]),[events,setEvents]=useState<Event[]>([]),[result,setResult]=useState<any>(null),[experiments,setExperiments]=useState<any[]>([]),[comparison,setComparison]=useState<Comparison[]>([]),[report,setReport]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const q=`symbol=${symbol}&timeframe=5m&start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}&limit=5000`;const [c,e,x,cmp,rp]=await Promise.all([fetch(`${API}/market-data/candles?${q}`),fetch(`${API}/market-data/smc-events?${q}`),fetch(`${API}/experiments?limit=20`),fetch(`${API}/experiments/comparison?limit=20`),fetch(`${API}/experiments/report?limit=20`)]);if(!c.ok)throw new Error(await c.text());if(!e.ok)throw new Error(await e.text());setCandles(await c.json());setEvents(await e.json());if(x.ok)setExperiments(await x.json());if(cmp.ok){const body=await cmp.json();setComparison(body.results||[])}if(rp.ok){const body=await rp.json();setReport(body.content||"")} }catch(err){setError(err instanceof Error?err.message:"Request failed")}finally{setLoading(false)}};
 const runBacktest=async()=>{setLoading(true);setError("");try{const r=await fetch(`${API}/backtest/run`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol,timeframe:"5m",start,end,strategy:"Liquidity MSS FVG",initial_capital:"100000",risk_per_trade:"0.005",reward_risk:"3",slippage_bps:"1",limit:5000})});if(!r.ok)throw new Error(await r.text());setResult(await r.json())}catch(err){setError(err instanceof Error?err.message:"Backtest failed")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 return <main className="shell"><div className="topbar"><div><div className="brand">Advance Trading System</div><div className="muted">Indian market research dashboard</div></div><span className="muted">PostgreSQL-backed · deterministic SMC</span></div><section className="card"><div className="controls"><input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} aria-label="Symbol"/><input value={start} onChange={e=>setStart(e.target.value)} aria-label="Start"/><input value={end} onChange={e=>setEnd(e.target.value)} aria-label="End"/><button onClick={load} disabled={loading}>Load market data</button><button onClick={runBacktest} disabled={loading||!candles.length}>Run backtest</button></div>{error&&<p className="error">{error}</p>}<CandlestickChart candles={candles} events={events}/></section><div className="grid" style={{marginTop:18}}><section className="card"><h2>SMC events</h2><SignalOverlay events={events}/></section><section className="card"><h2>Backtest results</h2><BacktestResults result={result}/></section></div><section className="card" style={{marginTop:18}}><h2>Experiments</h2><ExperimentTable experiments={experiments}/></section><section className="card" style={{marginTop:18}}><h2>Strategy comparison</h2>{comparison.length?<div>{comparison.map((item,index)=><div key={item.experiment_id} style={{display:"grid",gridTemplateColumns:"40px 1fr 120px 120px 120px",gap:12,padding:"8px 0",borderBottom:"1px solid #eee"}}><strong>#{index+1}</strong><span>{item.experiment_id} · {item.strategy_version}</span><span>Return {item.total_return}</span><span>Drawdown {item.max_drawdown}</span><span>Trades {item.trade_count}</span></div>)}</div>:<p className="muted">No persisted experiment results available.</p>}</section><section className="card" style={{marginTop:18}}><h2>Research report</h2>{report?<pre style={{whiteSpace:"pre-wrap",margin:0}}>{report}</pre>:<p className="muted">Create an experiment to generate a comparison report.</p>}</section></main>}
